# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "github_actions:pull-request"
    commit-message:
      prefix: meta
    open-pull-requests-limit: 10
  - package-ecosystem: npm # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    labels:
      - "github_actions:pull-request"
    commit-message:
      prefix: meta
    groups:
      lint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
          - "stylelint"
          - "stylelint-*"
        exclude-patterns:
          - "eslint-plugin-storybook"
      next-js:
        patterns:
          - "next"
          - "turbo"
          - "next-mdx-remote"
          - "next-sitemap"
          - "next-themes"
          - "@vercel/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      tailwind:
        patterns:
          - "@savvywombat/tailwindcss-grid-areas"
          - "prettier-plugin-tailwindcss"
          - "tailwindcss"
    ignore:
      # Manually update major versions of @types/node with the version specified within .nvmrc
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 10
